---

- name: common settings
  hosts: default
  vars_files: [ vars/common.yml ]
  roles:
    - common

- name: setup NFS server
  hosts: nfs_server
  roles:
    - nfs_server

- name: nfs client
  hosts: default
  roles:
    - nfs_client

- name: setup LDAP server
  hosts: ldap_server
  vars_files: [ vars/ldap.yml ]
  roles:
    - ldap_server

- name: ldap client
  hosts: default
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_client

- name: ldap users
  hosts: ldap_server
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_users

- name: make ldap_sudo sudoers
  hosts: default
  roles:
    - ldap_sudoers
    
- name: desktop environment
  hosts: desktop
  roles:
    - desktop_common

- name: OFED and CUDA (install on all nodes, including CPU)
#  hosts: none
  hosts: default
  roles:
    - mlnx_ofed
    - nvidia_cuda_toolkit

- name: gpu-only software
#  hosts: none
  hosts: gpu
  roles:
    - nvidia_persistenced
    # - nvidia_gpu_direct_storage

- name: install nvidia fabric manager on vms having nvswitch
  hosts: nvswitch
  roles:
    - nvidia_fabricmanager

- name: ucx and mpi
#  hosts: none
  hosts: default
  roles:
    - ucx
    - openmpi

- name: setup reverse proxy for jupyterlab
  hosts: reverseproxy
  roles:
    - reverse_proxy

- name: Lustre
  hosts: default
  roles:
    - lustre

