- name: update pci.ids
  shell: update-pciids

- name: download nvidia meta packages
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /opt/cuda-keyring_1.1-1_all.deb

- name: install nvidia repository
  apt:
    deb: /opt/cuda-keyring_1.1-1_all.deb

- name: install nvidia drivers
  apt:
    update_cache: yes
    name:
      - nvidia-headless-535
      - nvidia-utils-535

- name: install cuda-toolkit
  apt:
    name: cuda-toolkit-11-8
    update_cache: yes

- name: put /etc/modules-load.d/nvidia-peermem.conf
  blockinfile:
    path: /etc/modules-load.d/nvidia-peermem.conf
    create: yes
    marker: ""
    block: |
      nvidia-peermem

- name: install libcudnn and nccl
  apt:
    update_cache: yes
    name:
      - libcudnn8
      - libcudnn8-dev
      - libnccl2
      - libnccl-dev

- name: add path for CUDA to system-wide bashrc
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
      export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

