- name: make /opt/gpu_direct
  file:
    path: /opt/gpu_direct
    state: directory

- name: copy patch files
  copy:
    src: "{{ item }}"
    dest: /opt/gpu_direct
  with_items:
    - ./files/000-gdrcopy-2.3.1.patch

- name: install nvidia direct storage packages
  apt:
    update_cache: yes
    name:
      - check
      - libsubunit0
      - libsubunit-dev
      - build-essential
      - devscripts
      - debhelper
      - check
      - libsubunit-dev
      - fakeroot
      - pkg-config
      - dkms
      - nvidia-gds-11-8

- name: unarchive v2.3.1-1.tar.gz
  unarchive:
    remote_src: yes
    src: https://github.com/NVIDIA/gdrcopy/archive/refs/tags/v2.3.1-1.tar.gz
    dest: /opt/gpu_direct

- name: compile
  shell: |
    cd /opt/gpu_direct/gdrcopy-2.3.1-1
    patch -p0 < /opt/gpu_direct/000-gdrcopy-2.3.1.patch
    cd packages
    CUDA=/usr/local/cuda-11.8 ./build-deb-packages.sh

- name: install gdrcopy debs
  apt:
    deb: "{{ item }}"
  with_items:
    - /opt/gpu_direct/gdrcopy-2.3.1-1/packages/gdrdrv-dkms_2.3.1_amd64.Ubuntu22_04.deb
    - /opt/gpu_direct/gdrcopy-2.3.1-1/packages/libgdrapi_2.3.1_amd64.Ubuntu22_04.deb
    - /opt/gpu_direct/gdrcopy-2.3.1-1/packages/gdrcopy-tests_2.3.1_amd64.Ubuntu22_04.deb
    - /opt/gpu_direct/gdrcopy-2.3.1-1/packages/gdrcopy_2.3.1_amd64.Ubuntu22_04.deb

