- name: install related packages
  apt:
    update_cache: yes
    name:
      - libfuse3-dev
      - libnuma-dev
      - binutils-dev

- name: get sources
  get_url:
    url: https://github.com/openucx/ucx/releases/download/v1.14.1/ucx-1.14.1.tar.gz
    dest: /tmp/ucx-1.14.1.tar.gz

- name: unarchive
  shell: tar zxvf /tmp/ucx-1.14.1.tar.gz -C /tmp/

- name: compile and install
  shell: |
    cd /tmp/ucx-1.14.1
    ./contrib/configure-release-mt --prefix=/usr/local/ucx-1.14.1 --with-cuda=/usr/local/cuda-11.8 --with-gdrcopy --enable-optimizations
     make -j
     make install

- name: apt clean
  shell: apt clean

- name: Reboot
  reboot: reboot_timeout=120

- name: Ping connection
  ping:

