# Role: Lustre
# Configure Lustre 

- name: get storage network interface name (ens1??)
  shell: ip -br addr | grep {{ rdmaipv4 }} | awk '{print $1}'
  register: cmd_res

# - name: show storage network interface name
#   debug:
#     msg: "{{ cmd_res }}"

- name: set tpc_netif, tcp_src_ipaddr, ib_src_ipaddr
  set_fact:
    ib_netif: "{{ cmd_res.stdout }}"
    tcp_netif: "{{ cmd_res.stdout }}"
    tcp_src_ipaddr: "{{ rdmaipv4 }}"
    ib_src_ipaddr: "{{ rdmaipv4 }}"

# - name: show storage network interface name
#   debug:
#     msg: "{{ ib_netif }}, {{ tcp_netif }}, {{ tcp_src_ipaddr }}, {{ ib_src_ipaddr }}"

- name: generate lnet.conf.ddn
  template:
    src: templates/lnet.conf.ddn.j2
    dest: /etc/lnet.conf.ddn

- name: add entry to /etc/fstab    
  blockinfile:
    path: /etc/fstab
    block: |
      # lustre
      172.17.8.40@{{ lnet }}:172.17.8.41@{{ lnet }}:/fast  /data  lustre network={{ lnet }},flock,noauto,defaults 0 0
      172.17.8.56@{{ lnet }}:172.17.8.57@{{ lnet }}:/large /model lustre network={{ lnet }},flock,noauto,defaults 0 0

- name: lustre.conf
  template:
    src: templates/lustre.conf.j2
    dest: /etc/modprobe.d/lustre.conf

- name: get lustre_client version
  shell: dkms status | grep lustre-client-modules  | grep $(uname -r) | awk -F'[/,]' '{print $2}'
  register: lustre_ver
# - debug: msg="{{ lustre_ver.stdout }}"

- name: get linux kernel version
  shell: uname -r
  register: linux_ver
# - debug: msg="{{ linux_ver.stdout }}"

- name: uninstall lustre_client dkms module
  shell: dkms uninstall -m lustre-client-modules -v {{ lustre_ver.stdout }} -k {{ linux_ver.stdout }}

- name: remove lustre_client dkms module
  shell: dkms remove -m lustre-client-modules -v {{ lustre_ver.stdout }} -k {{ linux_ver.stdout }}

- name: build lustre_client dkms module
  shell: dkms build -m lustre-client-modules -v {{ lustre_ver.stdout }} -k {{ linux_ver.stdout }}

- name: install lustre_client dkms module
  shell: dkms install -m lustre-client-modules -v {{ lustre_ver.stdout }} -k {{ linux_ver.stdout }}

- name: enable lustre
  systemd:
    name: lustre_client
    enabled: true
    state: restarted
    
