# Role: Lustre
# Configure Lustre 

- name: get storage network interface name (ens1??)
  shell: ip -br addr | grep {{ rdmaipv4 }} | awk '{print $1}'
  register: cmd_res

# - name: show storage network interface name
#   debug:
#     msg: "{{ cmd_res }}"

- name: set tpc_netif, tcp_src_ipaddr, ib_src_ipaddr
  set_fact:
    ib_netif: "{{ cmd_res.stdout }}"
    tcp_netif: "{{ cmd_res.stdout }}"
    tcp_src_ipaddr: "{{ rdmaipv4 }}"
    ib_src_ipaddr: "{{ rdmaipv4 }}"

# - name: show storage network interface name
#   debug:
#     msg: "{{ ib_netif }}, {{ tcp_netif }}, {{ tcp_src_ipaddr }}, {{ ib_src_ipaddr }}"

- name: generate lnet.conf.ddn
  template:
    src: templates/lnet.conf.ddn.j2
    dest: /etc/lnet.conf.ddn

- name: add entry to /etc/fstab    
  blockinfile:
    path: /etc/fstab
    block: |
      # lustre
      172.17.8.40@{{ lnet }}:172.17.8.41@{{ lnet }}:/fast  /fast  lustre network={{ lnet }},flock,noauto,defaults 0 0
      172.17.8.56@{{ lnet }}:172.17.8.57@{{ lnet }}:/large /large lustre network={{ lnet }},flock,noauto,defaults 0 0

- name: lustre.conf
  template:
    src: templates/lustre.conf.j2
    dest: /etc/modprobe.d/lustre.conf

- name: enable lustre
  systemd:
    name: lustre_client
    enabled: true
    state: restarted
    
