---

# Role: OpenMPI
# Install OpenMPI

- name: copy env files
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d
  with_items:
    - ./files/openmpi.sh

- name: make /opt/openmpi
  file:
    path: /opt/openmpi
    state: directory

- name: download and unarchive OpenMPI
  unarchive:
    src: https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5.tar.bz2
    dest: /opt/openmpi
    remote_src: yes

- name: compile and install
  shell: |
    cd /opt/openmpi/openmpi-4.1.5/
    mkdir build-gpu
    cd build-gpu
    ../configure --prefix=/usr/local/openmpi-4.1.5 --with-ucx=/usr/local/ucx-1.14.1 --with-platform=../contrib/platform/mellanox/optimized --with-cuda=/usr/local/cuda-11.8
    make -j
    make install

